title: "Mandacaru Community"
description: "Fomentando a comunidade Empreendedora em Pernambuco! 🌵"

social:
  github: "https://github.com/MandacaruCommunity"
  twitter: "https://twitter.com/mandacarucommunity"
  facebook: "http://fb.com/https://github.com/MandacaruCommunity"
